### ISSUE TITLE
Lifetime expectation

### ISSUE THREAD

**Issue by milouse** [Nitrokey/nitrokey-pro-hardware#21]
Hi,

I’m an happy user of a nittrokey pro from 2016. Recently I began to encounter some glitches (the key "block" indefinitely with red led up and fix until I unplug it and plug it again). They make me wonder how many time a nitrokey is expected to last? As I use it to encrypt a lot of my secret (including some encrypted harddrive), losing it without notice is not really an option. Thus I’m wondering if it’s time to think about a new one or if normally they are built to last 20-30 year?

Thank you very much.

**Comment by jans23** [comment]
From the [factsheet](https://www.nitrokey.com/files/doc/Nitrokey_Pro_factsheet.pdf):

* Life expectancy (MTBF, MTTF): >100,000 PIN entries
* Durability USB connector (EIA-364-09): >1,500 mate and unmate cycles
* Storage time: >20 years

**Comment by szszszsz** [comment]
Hi!
This might be a symptom of a known firmware issue: https://github.com/Nitrokey/nitrokey-pro-firmware/issues/54.
In case the locking issue does not happen when only the smart card services are used, then I would say it is expected as of the current state.
I believe the numbers provided by Jan are correct in practice. I have not broken my devices since 2016 yet as well (and I have tested and used them extensively). Nevertheless, please keep in mind to have key backups (in the cold storage or on other Nitrokeys) for any cases of the hardware failure (so it would not become the single point of failure in your system setup).

Closing as done. Please reopen if that does not answer your question.

**Comment by milouse** [comment]
Thank you very much for your answers! I reassure you I regularly do some backup. But my question was more to be prepared about switching properly from one key to a new one while the older is still working, instead of being obliged to make an emergency purchase/delivery of a new one and restart from backup once the old one die ;)

I might already have crossed https://github.com/Nitrokey/nitrokey-pro-firmware/issues/54, but the current behavior only involved the smartcard alone (i.e. hang on decrypting something after some inactivity). That said, I also wonder if it could not be related to a general OS update (like gpg or the smartcard being lost after a suspend?). I’ll watch in the near future how it evolves.
